name: Check chains configuration files

on:
  workflow_dispatch:
  pull_request:

jobs:
  check-chain-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 🟩 Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ⚙️ Install dependencies
        run: npm install
        shell: bash

      - name: 📝 Check chain config files
        run: npm run check:chains-file
