name: Generate metadata file

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  metadata-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 🛠 Set up env variables
        uses: ./.github/workflows/setup-env

      - name: 📝 Update chains file
        run: |
          cd metadataCreator
          npm install
          npm run start

      - name: Make Pull Request
        uses: ./.github/workflows/make-pull-request
        with:
          commit-files: chains/**/*.md
          commit-message: Update chains/readme.md
          app-id: ${{ secrets.PR_APP_ID}}
          app-token: ${{ secrets.PR_APP_TOKEN}}
          branch-name: update-chains-readme
          pr-title: Update project overal data
          pr-body:
            This PR was generated automatically by the GitHub Action, **generate_metadata**.

            Feel free to close this PR if the changes are not needed.
          pr-base: main
